### ISSUE TITLE
Fix Integration Test Failures in PDF Discovery

### ISSUE THREAD

**Issue by bouthilx** [bouthilx/compute-forecast-framework#167]
## Description
Fix integration test failures in PDF discovery identified in PR #139.

### ArXiv Collector Errors
All errors follow the same pattern:
- Error: `No arXiv ID for paper_X` (where X is 1, 3, 5, 7, 9, 11, 13, 15, 17, 19)
- Root cause: ArXiv collector expects papers to have arXiv IDs but test papers don't have them

## Error Log
```
ERROR compute_forecast.pdf_discovery.core.collectors:collectors.py:93 Error discovering PDF for paper_1 from arxiv: No arXiv ID for paper_1
ERROR compute_forecast.pdf_discovery.core.collectors:collectors.py:93 Error discovering PDF for paper_3 from arxiv: No arXiv ID for paper_3
ERROR compute_forecast.pdf_discovery.core.collectors:collectors.py:93 Error discovering PDF for paper_5 from arxiv: No arXiv ID for paper_5
ERROR compute_forecast.pdf_discovery.core.collectors:collectors.py:93 Error discovering PDF for paper_7 from arxiv: No arXiv ID for paper_7
ERROR compute_forecast.pdf_discovery.core.collectors:collectors.py:93 Error discovering PDF for paper_9 from arxiv: No arXiv ID for paper_9
ERROR compute_forecast.pdf_discovery.core.collectors:collectors.py:93 Error discovering PDF for paper_11 from arxiv: No arXiv ID for paper_11
ERROR compute_forecast.pdf_discovery.core.collectors:collectors.py:93 Error discovering PDF for paper_13 from arxiv: No arXiv ID for paper_13
ERROR compute_forecast.pdf_discovery.core.collectors:collectors.py:93 Error discovering PDF for paper_15 from arxiv: No arXiv ID for paper_15
ERROR compute_forecast.pdf_discovery.core.collectors:collectors.py:93 Error discovering PDF for paper_17 from arxiv: No arXiv ID for paper_17
ERROR compute_forecast.pdf_discovery.core.collectors:collectors.py:93 Error discovering PDF for paper_19 from arxiv: No arXiv ID for paper_19
```

## Priority
Medium - Integration test infrastructure

## Acceptance Criteria
- [ ] All 10 integration test errors resolved
- [ ] ArXiv collector gracefully handles papers without arXiv IDs
- [ ] Test papers properly configured with necessary IDs
- [ ] No error logs for expected scenarios
